Leaderboard/Leaderboard/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

Leaderboard/app/urls.py
from django.urls import path, include
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('upload/', views.upload, name='upload'),
    path('show/', views.show, name='show'),
]

Leaderboard/app/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


# Create your models here.

# 分数表
class Score(models.Model):
    client = models.CharField(verbose_name='客户端号', max_length=16, unique=True)
    score = models.IntegerField(verbose_name='分数', default=0,
                                validators=[MaxValueValidator(10000000), MinValueValidator(1)])

    def __str__(self):
        return f'{self.client}'

    class Meta:
        verbose_name = '分数登记表'
        verbose_name_plural = verbose_name


# 名次表
class Rank(models.Model):
    c_id = models.OneToOneField(Score, on_delete=models.CASCADE, primary_key=True, )
    rank = models.IntegerField(verbose_name='名次', validators=[MinValueValidator(1)])

Leaderboard/app/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from app.models import Score, Rank


# Create your views here.

# 登陆
@csrf_exempt
def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)  # 根据获取的用户名密码去数据库查询，并返回user对象
        if user is not None and user.is_active:
            auth.login(request, user)
            return JsonResponse({'status': 200})
        else:
            return JsonResponse({'status': 400, 'errmsg': '账号或密码错误'})


# 登出
def logout(request):
    auth.logout(request)  # 从请求中删除经过身份验证的用户的ID并刷新其会话数据。
    return redirect('/')


@login_required(login_url='/')
@csrf_exempt
def upload(request):
    if request.method == 'GET':
        user = request.user
        return render(request, 'upload.html', {'user': user})
    if request.method == 'POST':
        # 接受页面上传的数据
        score = request.POST.get('score', '')
        if score:
            # 获取数据库的数据
            old_scor = Score.objects.filter(client=request.user).first()
            if old_scor:
                if old_scor.score != score:
                    old_scor.score = score
                    old_scor.save()
            else:
                Score.objects.create(client=request.user, score=score)
            # 排名表数据更新
            Rank.objects.all().delete()
            score_li = [score_obj.id for score_obj in Score.objects.all().order_by('-score')]
            n = 1
            for i in score_li:
                Rank.objects.create(c_id_id=i, rank=n)
                n = n + 1
            return JsonResponse({'status': 'sucess'})
        return JsonResponse({'status': 'error'})


@login_required(login_url='/')
@csrf_exempt
def show(request):
    context = {'scores': [{'ranking': scor.rank.rank, 'client': scor.client, 'score': scor.score} for scor in
                          Score.objects.all().order_by('-score')]}
    if request.method == 'GET':
        count = Score.objects.all().count()
        uscore = Score.objects.filter(client=request.user).first()
        uscore = {'ranking': uscore.rank.rank, 'score': uscore.score}
        return render(request, 'show.html', {'context': context, 'count': count, 'uscore': uscore})
    if request.method == 'POST':
        try:
            start = int(request.POST.get('start'))
            end = int(request.POST.get('end'))
        except ValueError as e1:
            return JsonResponse({'status': 'error'})
        context = {'scores': [{'ranking': scor.rank.rank, 'client': scor.client, 'score': scor.score} for scor in
                              Score.objects.all().order_by('-score')[start - 1:end]]}
        return JsonResponse({'status': 'ok', 'context': context})

Leaderboard/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<h1 align="center">登录</h1>
<table align="center">
    <tr>
        <th>用户名：</th>
        <td>
            <input type="text" name="username" id="username">
            <div id="username_err" style="color: red;"></div>
        </td>

    </tr>

    <tr>
        <th>密码：</th>
        <td>
            <input type="password" name="password" id="password">
            <div id="password_err" style="color: red;"></div>
        </td>

    </tr>

    <tr>
        <th></th>
        <td>
            <input type="button" onclick="submit()" value="登录">
            <div id="err" style="color: red;"></div>
        </td>

    </tr>
</table>
<script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
<script>
    function submit() {
        var username = $('#username').val();
        var password = $('#password').val();
        var flag = true;
        if(!username){
            $('#username_err').text('请输入用户名！');
            flag = false
        }
        if (!password){
            $('#password_err').text('请输入密码！');
            flag = false
        }
        var data = {'username':username,'password':password};
        if(flag){
            $.ajax({
                url: '',
                data: data,
                type: 'POST',
                success: function (res) {
                    if(res.status > 200){
                        $('#err').text(res.errmsg);
                    }else {
                        location.href = '/upload/'
                    }

                },error: function (e) {
                    console.log(e)
                }
            })
        }
        return flag
    }
</script>
</body>
</html>

Leaderboard/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查询</title>
</head>
<body>
&nbsp;
<a href="{% url 'app:upload' %}"><input name="" type="button" value="上传页面"/></a>&nbsp;&nbsp;
<a href="/logout/"><input name="" type="button" value="退出"/></a>
<div id="table1">
    <table border="1px" width="300px" cellspacing="0px" align="center">
        <thead>
        <tr>
            <th>排名</th>
            <th>客户端</th>
            <th>分数</th>
        </tr>
        </thead>

        <tbody>
        {% for item in context.scores %}
            <tr>
                <td>{{ item.ranking }}</td>
                <td>{{ item.client }}</td>
                <td>{{ item.score }}</td>
            </tr>
        {% endfor %}
        <tr>
            <td>{{ uscore.ranking }}</td>
            <td>{{ user }}</td>
            <td>{{ uscore.score }}</td>
        </tr>
        </tbody>
    </table>
</div>

<h5>请输入要查询名次范围：第
    <input type="text" id="start" name="start" placeholder="请输入起始名次，例如:10">
    至
    <input type="text" id="end" name="end" placeholder="请输入终止名次，例如:20">名。&nbsp;&nbsp;
    <input name="submit" id="submit" type="button" value="查询" onclick="return f()"/>
</h5>
<div id="start_err" style="color: red;"></div>
<div id="end_err" style="color: red;"></div>
<div id="table2" style="display: none">
    <table border="1px" width="300px" cellspacing="0px" align="center">
        <thead>
        <tr>
            <th>排名</th>
            <th>客户端</th>
            <th>分数</th>
        </tr>
        </thead>

        <tbody id="tbody2"></tbody>
        <tr>
            <td>{{ uscore.ranking }}</td>
            <td>{{ user }}</td>
            <td>{{ uscore.score }}</td>
        </tr>
    </table>
</div>

<script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>

<script type="text/javascript">
    var context2;

    function f() {
        var start = $('#start').val();
        var end = $('#end').val();
        var flag = true;
        if (start < 0) {
            $('#start_err').text('起始名次不支持负数！');
            flag = false;
        }
        if (end < 0) {
            $('#end_err').text('终止名次不支持负数！');
            flag = false;
        }
        if (flag) {
            $.ajax({
                url: '/show/',
                data: {'start': start, 'end': end},
                type: 'POST',
                success: function (result) {
                    if (result['status']=='ok'){
                    $('#table1').hide();
                    $('#table2').show();
                    context2 = result['context'];
                    $("#tbody2").empty();
                    $.each(context2['scores'], function (index, item) {
                        $('#tbody2').append('<tr><td>' + item['ranking'] + '</td><td>' +
                            item['client'] + '</td><td>' + item['score'] + '</td></tr>');
                    });
                    }else{
                        alert('请输入合法的名次！名次为数值型且为整数。')
                    }
                },

            })
        }
        return flag;
    }
</script>

</body>
</html>

Leaderboard/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传</title>
</head>
<body>
<form method="post">
    <h3>
        当前客户端 {{ user }}，请上传分数：<input type="text" id="score" name="score" placeholder="可输入范围：1~10000000。"> 分。
        &nbsp;&nbsp;&nbsp;&nbsp;
        <input name="" type="button" value="提交" onclick="return sub()"/><div id="score_err" style="color: red;"></div>
        <div id="score_err" style="color: red;"></div>
    </h3>
</form>
&nbsp;&nbsp;
<a href="{% url 'app:show' %}"><input name="" type="button" value="查询"/></a>
&nbsp;&nbsp;
<a href="/logout/"><input name="" type="button" value="退出"/></a>
 
<script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
<script type="text/javascript">
    function sub() {
        var score = $('#score').val();
        var flag = true;
        if (score < 1 || score > 10000000) {
            $('#score_err').text('分数不符合规范！');
            flag = false;
        }
        if (flag) {
            $.ajax({
                url: '/upload/',
                data: {'score': score},
                type: 'POST',
                success: function (result) {
                    alert(result.status)
                }
            })
        }
        return flag;
    }
</script>
 
</body>
</html>